name: BNRC Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '35 4 * * *'   # 10:00 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Clean screenshots
      run: rm -rf BNRCscreenshots/*

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # ✅ Run tests and capture results
    - name: Run Playwright tests
      run: |
        npx playwright test test/e-applications/certificate.spec.js --project=chromium > cert-report.json
        if [ -d playwright-report ]; then mv playwright-report playwright-report-cert; fi
        npx playwright test test/e-applications/transfer.spec.js --project=chromium > transfer-report.json
        if [ -d playwright-report ]; then mv playwright-report playwright-report-transfer; fi
        npx playwright test test/e2e/PRERNA-event.spec.js --project=chromium > prerna-report.json
        if [ -d playwright-report ]; then mv playwright-report playwright-report-prerna; fi

    - name: Upload HTML reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-html-reports
        path: |
          playwright-report-cert
          playwright-report-transfer
          playwright-report-prerna
        if-no-files-found: ignore
        retention-days: 7
    # ✅ Send email AFTER tests
    - name: Send email notification
      if: github.event_name != 'push'
      run: node utils/sendEmail.js
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}